package com.ebirth.service;

import com.ebirth.model.BirthInfo;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.util.Matrix;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

@Service
public class CertificatePdfService {

    public byte[] generateCertifiedCertificate(BirthInfo birthInfo) throws IOException {
        try (PDDocument document = new PDDocument();
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {

            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            try (PDPageContentStream content = new PDPageContentStream(document, page)) {
                drawHeader(content, page);
                drawBirthDetails(content, birthInfo);
                drawWatermark(content, page);
                drawFooter(content, page);
            }

            document.save(outputStream);
            return outputStream.toByteArray();
        }
    }

    private void drawHeader(PDPageContentStream content, PDPage page) throws IOException {
        float top = page.getMediaBox().getHeight() - 80;

        content.beginText();
        content.setFont(PDType1Font.HELVETICA_BOLD, 22);
        content.newLineAtOffset(130, top);
        content.showText("Birth Certificate");
        content.endText();

        content.beginText();
        content.setFont(PDType1Font.HELVETICA, 12);
        content.newLineAtOffset(175, top - 24);
        content.showText("Official Extract");
        content.endText();
    }

    private void drawBirthDetails(PDPageContentStream content, BirthInfo birthInfo) throws IOException {
        float x = 70;
        float y = 660;
        float step = 28;

        writeLine(content, x, y, "Full Name: " + safe(birthInfo.getFullName()));
        writeLine(content, x, y - step, "Date of Birth: " + safeDate(birthInfo));
        writeLine(content, x, y - (step * 2), "Place of Birth: " + safe(birthInfo.getPlaceOfBirth()));
        writeLine(content, x, y - (step * 3), "Father Name: " + safe(birthInfo.getFatherName()));
        writeLine(content, x, y - (step * 4), "Mother Name: " + safe(birthInfo.getMotherName()));
        writeLine(content, x, y - (step * 5), "Address: " + safe(birthInfo.getAddress()));
        writeLine(content, x, y - (step * 7), "Status: CERTIFIED");
    }

    private void writeLine(PDPageContentStream content, float x, float y, String text) throws IOException {
        content.beginText();
        content.setFont(PDType1Font.HELVETICA, 12);
        content.newLineAtOffset(x, y);
        content.showText(text);
        content.endText();
    }

    private void drawWatermark(PDPageContentStream content, PDPage page) throws IOException {
        content.saveGraphicsState();
        content.setNonStrokingColor(220, 220, 220);
        content.transform(Matrix.getRotateInstance(Math.toRadians(35), 240, 380));
        content.beginText();
        content.setFont(PDType1Font.HELVETICA_BOLD, 72);
        content.newLineAtOffset(60, 20);
        content.showText("CERTIFIED");
        content.endText();
        content.restoreGraphicsState();
    }

    private void drawFooter(PDPageContentStream content, PDPage page) throws IOException {
        content.beginText();
        content.setFont(PDType1Font.HELVETICA_OBLIQUE, 10);
        content.newLineAtOffset(70, 70);
        content.showText("Generated by eBirth Verification System");
        content.endText();
    }

    private String safe(String value) {
        return value == null ? "-" : value;
    }

    private String safeDate(BirthInfo birthInfo) {
        return birthInfo.getDateOfBirth() == null ? "-" : birthInfo.getDateOfBirth().toString();
    }
}
